From camunda/camunda-bpm-platform

ENV DB_DRIVER=org.postgresql.Driver
ENV DB_URL=jdbc:postgresql://container-postgresql:5432/dblocal
ENV DB_USERNAME=postgres
ENV DB_PASSWORD=postgres
ENV WAIT_FOR=container-postgresql:5432

EXPOSE 8080
