apiVersion: v1
kind: Service
metadata:
  name: container-mailserver
spec:
  ports:
    - name: http
      port: 1080
      targetPort: 1080
    - name: smtp
      port: 1025
      targetPort: 1025
  selector:
    app: container-mailserver
  type: NodePort
