apiVersion: v1
kind: Service
metadata:
  name: container-rabbitmq
spec:
  ports:
    - name: httpb
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
  selector: 
    app: container-rabbitmq
  type: NodePort